weights: QAT/../checkpoints/yolov5l.pt
cfg: ./QAT/models/yolov5l.yaml
data: ./dataset/coco.yaml
hyp: ./dataset/hyps/hyp.scratch-low.yaml
epochs: 300
batch_size: 64
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: false
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: ./QAT/runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: None
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
weight: ./checkpoints/yolov5l.pt
upload_bucket: false
save_dir: QAT/runs/train/exp13
